FROM csiroenvinf/datapusher
MAINTAINER CSIRO

#tell python requests to use local certs rather than certifi
#ADD wildcard.research.csiro.au-qv-certs /sslcert
#ENV REQUESTS_CA_BUNDLE /sslcert/wildcard.research.csiro.au-full-chain.crt

