# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
ckan:
   # Note, if you are working on CKAN core, change this to
   build: ../../
   links:
      - db
      - solr
      - redis
      - datapusher 
   ports:
      - "${CKAN_HOST_PORT}:5000"
   environment:
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis
      - CKAN_SITE_URL=${CKAN_SITE_BASE_URL}:${CKAN_HOST_PORT}
      - CKAN_PORT=$CKAN_PORT
      - DATASTORE_READONLY_PASSWORD=$DATASTORE_READONLY_PASSWORD
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CKAN_LDAP_PASSWORD=$CKAN_LDAP_PASSWORD
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_DATAPUSHER_URL=http://datapusher:8800

datapusher:
   image: clementmouchet/datapusher
   ports:
      - "${DATAPUSHER_HOST_PORT}:8800"

db:
  build: postgresql/
  environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

ckan_postgres_backup:
  image: prodrigestivill/postgres-backup-local
  volumes:
      - ${HOST_BACKUP_DIR}/postgres/ckan:/backups
  links:
      - db
  environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ckan
      - POSTGRES_USER=ckan
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_EXTRA_OPTS=--format=custom
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

datastore_postgres_backup:
  image: prodrigestivill/postgres-backup-local
  volumes:
      - ${HOST_BACKUP_DIR}/postgres/datastore:/backups
  links:
      - db
  environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=datastore
      - POSTGRES_USER=ckan
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_EXTRA_OPTS=--format=custom
      - SCHEDULE=@every 10s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
  
solr:
  image: ckan/solr:latest
      
redis:
  image: redis:latest
