# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
ckan:
  container_name: ckan
  # Note, if you are working on CKAN core, change this to
  build: ../../
  links:
      - db
      - solr
      - redis
  ports:
      - "80:5000"
  environment:
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis
      - CKAN_SITE_URL=$CKAN_SITE_URL
      - CKAN_PORT=$CKAN_PORT
      - DATASTORE_READONLY_PASSWORD=$DATASTORE_READONLY_PASSWORD
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CKAN_LDAP_PASSWORD=$CKAN_LDAP_PASSWORD
db:
  container_name: db
  build: postgresql/
  
solr:
  container_name: solr
  image: ckan/solr:latest
    
redis:
  container_name: redis
  image: redis:latest
